# Generated by Django 6.0.3 on 2026-03-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_university_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='user',
            name='university_confirmed',
            field=models.BooleanField(default=False, verbose_name='Университет подтверждён через email'),
        ),
    ]
