# Generated by Django 6.0.3 on 2026-03-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_university_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Факультет'),
        ),
    ]
