# Generated by Django 6.0.3 on 2026-03-21 09:39

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 21, 9, 39, 51, 711322, tzinfo=datetime.timezone.utc), verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
