# Generated by Django 6.0.3 on 2026-03-21 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_end',
            new_name='event_end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_start',
            new_name='event_start',
        ),
        migrations.AddField(
            model_name='event',
            name='registration_end',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 21, 10, 9, 10, 802943, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 21, 10, 9, 15, 15028, tzinfo=datetime.timezone.utc), verbose_name='Дата начала регистрации'),
            preserve_default=False,
        ),
    ]
