# Generated by Django 6.0.3 on 2026-03-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_date_end_event_event_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='approved',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Не рассмотрено'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
