# Generated by Django 6.0.3 on 2026-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form',
            field=models.JSONField(blank=True, default=dict, verbose_name='Поля формы регистрации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
    ]
