# Generated by Django 6.0.3 on 2026-03-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_form_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='form_answer',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ответы на форму регистрации'),
        ),
    ]
