# Generated by Django 6.0.3 on 2026-03-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventregistration_form_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form_type',
            field=models.CharField(choices=[('site', 'Шаблон сайта'), ('yandex', 'Яндекс Формы'), ('google', 'Google Формы')], default='site', max_length=10, verbose_name='Тип формы регистрации'),
        ),
        migrations.AddField(
            model_name='event',
            name='form_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на внешнюю форму'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='event_images/', verbose_name='Изображение'),
        ),
    ]
