# Generated by Django 6.0.3 on 2026-03-22 07:26

import helpers.random_file_name
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventtag_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.random_file_name.RandomFileName('event_images'), verbose_name='Изображение'),
        ),
    ]
