# Generated by Django 6.0.3 on 2026-03-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_form_type_event_form_url_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='access_type',
            field=models.CharField(choices=[('open', 'Открытое'), ('university_only', 'Только для студентов вуза организатора'), ('closed', 'Закрытое')], default='open', max_length=20, verbose_name='Тип доступа'),
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.JSONField(blank=True, default=list, verbose_name='Категории'),
        ),
    ]
