# Generated by Django 6.0.3 on 2026-03-22 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='Внешняя форма регистрации'),
        ),
        migrations.CreateModel(
            name='ExternalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, verbose_name='Ссылка на форму')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='Маппинг полей формы')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_form', to='events.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Внешняя форма',
                'verbose_name_plural': 'Внешние формы',
            },
        ),
    ]
