# Generated by Django 6.0.3 on 2026-03-22 08:36

import helpers.nd_array_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='embedding',
            field=helpers.nd_array_field.NDArrayField(blank=True, null=True),
        ),
    ]
