# Generated by Django 6.0.3 on 2026-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_is_external_externalform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalform',
            name='url',
        ),
        migrations.AddField(
            model_name='externalform',
            name='parsed_form',
            field=models.JSONField(default=dict, verbose_name='Распарсенная форма (read_form)'),
        ),
    ]
