# Generated by Django 6.0.3 on 2026-03-22 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_externalform_url_externalform_parsed_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalform',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_form', to='events.event', verbose_name='Внешнее событие'),
        ),
    ]
