# Generated by Django 6.0.3 on 2026-03-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_embedding'),
        ('events', '0015_alter_externalform_event'),
    ]

    operations = [
    ]
