# Generated by Django 6.0.3 on 2026-03-22 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0005_user_course_user_university_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.university', verbose_name='Вуз организатора'),
        ),
    ]
